# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1bd9c02605ed294bd457ef1c59dd43017b8b71f7ed73ef77d6ed6fbdac6cc190714de7ad5d9ee17013325bc4b5063d3cdb5b94a19629abbfc96a6b245146ebc

test:
  secret_key_base: e5e53ccb347e3192769f24da9abceab3d1066407271037586a885613469efc6ae715ae52ef5b04b37b0a3568e38eb8a7aba35447ccc3590ed0a619f11ae50600

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
